### ISSUE TITLE
base n representations as Arrays of Ints

### ISSUE THREAD

**Issue by matthewleon** [sharkdp/purescript-bigints#16]
I propose `toBaseArray :: Int -> BigInt -> NonEmptyArray Int`.

**Comment by sharkdp** [comment]
Sounds like a useful addition!

What about calling this `digitsInBase` (and `digits = digitsInBase 10`) or similar?

**Comment by matthewleon** [comment]
> What about calling this digitsInBase (and digits = digitsInBase 10) or similar?

I like that.

**Comment by matthewleon** [comment]
referencing https://github.com/peterolson/BigInteger.js/issues/123

**Comment by sharkdp** [comment]
Closed via #17.

**Comment by sharkdp** [comment]
@matthewleon Let me know if you want me to release a new version.

**Comment by matthewleon** [comment]
Yes please. Thanks!

**Comment by sharkdp** [comment]
Done: https://pursuit.purescript.org/packages/purescript-bigints/3.5.0

**Comment by matthewleon** [comment]
Awesome! Thanks!
