### ISSUE TITLE
zshr

### ISSUE THREAD

**Issue by paulyoung** [sharkdp/purescript-bigints#21]
I realize that this is probably only missing because there isn’t an equivalent function in `big-integer` but I’m wondering if it could be defined in terms of the existing functions.

**Comment by paulyoung** [comment]
Maybe it’s just `zshr = shr <<< abs`?

**Comment by paulyoung** [comment]
Or rather, something similar that type checks 😄

**Comment by sharkdp** [comment]
I have never heard of this operation and I would rather not implement it here, if it is not included in `big-integer`.

**Comment by paulyoung** [comment]
That's fair enough.

FWIW it's the equivalent of this: https://pursuit.purescript.org/packages/purescript-integers/4.0.0/docs/Data.Int.Bits#v:zshr

**Comment by sharkdp** [comment]
Thank you for the clarification. If we should include this here, I think it would be best to ask for it to be included in `big-integer`.

**Comment by paulyoung** [comment]
I opened https://github.com/peterolson/BigInteger.js/issues/137.
