### ISSUE TITLE
Since JavaScript now has BigInt as a primitive type, should not purescript also support BigInt as a primitive type.

### ISSUE THREAD

**Issue by ghost** [sharkdp/purescript-bigints#24]
The BigInt's in purescript are very slow, since they are wrappers around a BigInteger.js module. Since JavaScript now supports BigInts as primitive types, should not PureScript also support BigInt natively using FFI, instead of these wrappers.

**Comment by sharkdp** [comment]
Maybe, but I guess it's better to discuss this on the PureScript repo.

**Comment by triallax** [comment]
@vamsikal3 I just want to point out that BigInteger.js actually uses native JavaScript `BigInt`s under the hood when they are available in the environment. You can see that in [BigInteger.js's README](https://github.com/peterolson/BigInteger).

Additionally, a lot of people use old browsers or ones that still don't support `BigInt`.

**Comment by radrow** [comment]
I totally agree, but this is not an issue to be solved in this repo, but rather in the PS itself

**Comment by triallax** [comment]
@radrow purescript/purescript#3848

**Comment by triallax** [comment]
Any reason this issue is still open? Like @sharkdp and @radrow said, this is not the appropriate repo for this issue.
