### ISSUE TITLE
Move to contrib?

### ISSUE THREAD

**Issue by jamesdbrock** [sharkdp/purescript-bigints#42]
There is talk on the Discord contrib channel about moving this repo to contrib so that the https://github.com/purescript-contrib/purescript-rationals package can depend on it.

https://discord.com/channels/864614189094928394/938253816862736405/981153724460335125

Are you willing to move this repo to contrib @sharkdp ?

**Comment by sharkdp** [comment]
> Are you willing to move this repo to contrib @sharkdp ?

Yes, absolutely. We also did so with some of my other packages. Let me know what I need to do.

**Comment by jamesdbrock** [comment]
> > Are you willing to move this repo to contrib @sharkdp ?
> 
> Yes, absolutely. We also did so with some of my other packages. Let me know what I need to do.

Thanks! Please transfer the repo. After that you can be involved as much or as little as you like. 

Would you like to still be the maintainer?
Would you like us to assign a new maintainer?
Would you like a co-maintainer?

**Comment by sharkdp** [comment]
> Thanks! Please transfer the repo. After that you can be involved as much or as little as you like.

Done.

> Would you like to still be the maintainer?

I think @thomashoneyman already agreed to be a maintainer. He should have full access rights anyway. At least he did before I moved the repo.

I don't need to be a maintainer anymore. None of my active projects depends on `bigints`, so I'm not that interested in the package anymore.

> Would you like us to assign a new maintainer?

That would be great.

**Comment by thomashoneyman** [comment]
Now that bigints is part of contrib (where I’m a member) it will receive maintenance from the whole team there — namely, updates for compiler changes or security issues or other general maintenance. For that reason I won’t be the “new maintainer”, but I’ll contribute to help with general maintenance. Thanks for your generosity with these libraries, @sharkdp!

**Comment by jamesdbrock** [comment]
Thanks for all the work you've done on this repo and others, @sharkdp !

**Comment by sharkdp** [comment]
Thank you for continuing maintenance!
