### ISSUE TITLE
Documentation doesn't match behavior for the function `not` (and possibly other functions)

### ISSUE THREAD

**Issue by Unisay** [sharkdp/purescript-bigints#6]
Doc says that function `not` inverts the bits.
In practice, however, the behavior is the following:
```
> bi = fromInt 42
> bin = toBase 2
> bin bi
"101010"

> bin (not bi)
"-101011"
```

where expected result for the `bin (not bi)` would be `10101`

**Comment by sharkdp** [comment]
Please see the upstream documentation here: https://github.com/peterolson/BigInteger.js#not
