### ISSUE TITLE
'big-integer' should be dependency

### ISSUE THREAD

**Issue by AidanDelaney** [sharkdp/purescript-bigints#7]
Hi,
I'm using a purescript module that depends on your purescript-bigints.  Somewhere along the line, on a clean install, I'm missing the npm [big-integer](https://www.npmjs.com/package/big-integer) package.  I guess that purescript-bigints depends on having the underlying 'big-integer' package installed?  If so, it may be useful to list it as a dependency.

**Comment by sharkdp** [comment]
big-integer is listed as an npm dependency:
https://github.com/sharkdp/purescript-bigints/blob/950bce2a4fda32fcfdc0dbb0a8597983c8a56ee4/package.json#L6-L8

It needs to be included via NPM, it does not work via bower (see README).
