### ISSUE TITLE
Add `fromNumber`

### ISSUE THREAD

**Issue by natefaubion** [sharkdp/purescript-bigints#9]
There's currently no way to lift a `Number` type into `BigInt`.

**Comment by sharkdp** [comment]
So I guess you'd like to have a way to avoid the `Int`-bottleneck in something like `fromInt <<< ceil` or `fromInt <<< round`?

**Comment by natefaubion** [comment]
Sorry, yes exactly.

**Comment by sharkdp** [comment]
Fix released in v3.4.0
